//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaBackEndService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginViewModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LoginViewModel : object
    {
        
        private string UserNameField;
        
        private string UserPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword
        {
            get
            {
                return this.UserPasswordField;
            }
            set
            {
                this.UserPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class UserModel : object
    {
        
        private string ApellidoField;
        
        private bool GrantedField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Granted
        {
            get
            {
                return this.GrantedField;
            }
            set
            {
                this.GrantedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaAlumnosViewModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ConsultaAlumnosViewModel : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string EmailField;
        
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        private string GradoField;
        
        private string NombreField;
        
        private string SexoField;
        
        private System.Nullable<double> TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grado
        {
            get
            {
                return this.GradoField;
            }
            set
            {
                this.GradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrearAlumnoViewModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CrearAlumnoViewModel : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string EmailField;
        
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        private int GradoField;
        
        private string NombreField;
        
        private int SexoField;
        
        private double TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grado
        {
            get
            {
                return this.GradoField;
            }
            set
            {
                this.GradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Response : object
    {
        
        private int ReturnCodeField;
        
        private string ReturnStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnString
        {
            get
            {
                return this.ReturnStringField;
            }
            set
            {
                this.ReturnStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SexoViewModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SexoViewModel : object
    {
        
        private string OpcionField;
        
        private int SexoIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opcion
        {
            get
            {
                return this.OpcionField;
            }
            set
            {
                this.OpcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SexoID
        {
            get
            {
                return this.SexoIDField;
            }
            set
            {
                this.SexoIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradosViewModel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class GradosViewModel : object
    {
        
        private string GradosField;
        
        private int IDGradosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grados
        {
            get
            {
                return this.GradosField;
            }
            set
            {
                this.GradosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrados
        {
            get
            {
                return this.IDGradosField;
            }
            set
            {
                this.IDGradosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PruebaTecnicaBackEndService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AuthenticateUser", ReplyAction="http://tempuri.org/IService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaBackEndService.UserModel> AuthenticateUserAsync(PruebaTecnicaBackEndService.LoginViewModel Accesos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultaAlumnos", ReplyAction="http://tempuri.org/IService/ConsultaAlumnosResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaBackEndService.ConsultaAlumnosViewModel[]> ConsultaAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarAlummnos", ReplyAction="http://tempuri.org/IService/InsertarAlummnosResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaBackEndService.Response> InsertarAlummnosAsync(PruebaTecnicaBackEndService.CrearAlumnoViewModel crearAlumnoViewModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultaSexos", ReplyAction="http://tempuri.org/IService/ConsultaSexosResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaBackEndService.SexoViewModel[]> ConsultaSexosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultaGrados", ReplyAction="http://tempuri.org/IService/ConsultaGradosResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaBackEndService.GradosViewModel[]> ConsultaGradosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceChannel : PruebaTecnicaBackEndService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PruebaTecnicaBackEndService.IService>, PruebaTecnicaBackEndService.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaBackEndService.UserModel> AuthenticateUserAsync(PruebaTecnicaBackEndService.LoginViewModel Accesos)
        {
            return base.Channel.AuthenticateUserAsync(Accesos);
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaBackEndService.ConsultaAlumnosViewModel[]> ConsultaAlumnosAsync()
        {
            return base.Channel.ConsultaAlumnosAsync();
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaBackEndService.Response> InsertarAlummnosAsync(PruebaTecnicaBackEndService.CrearAlumnoViewModel crearAlumnoViewModel)
        {
            return base.Channel.InsertarAlummnosAsync(crearAlumnoViewModel);
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaBackEndService.SexoViewModel[]> ConsultaSexosAsync()
        {
            return base.Channel.ConsultaSexosAsync();
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaBackEndService.GradosViewModel[]> ConsultaGradosAsync()
        {
            return base.Channel.ConsultaGradosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53231/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
